/*
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
*/
import Head from 'next/head';
import Navbar from "../components/Navbar";
import {connect} from "react-redux";
import {useState} from "react";

function HomePage(props) {
    const {user} = props;
    const [isChanged,setIsChanged] = useState(false);

    function changeName() {
        if (isChanged) {
            props.changeName('Ali')
        } else {
            props.changeName('Asilbek')
        }
        setIsChanged(!isChanged)
    }

    return (
        <div>
            <Head>
                <title> Home page </title>
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar/>
                <div className="container">
                    <div className="text-center mt-2">
                        <h4> Home page ---- redux </h4>
                    </div>
                    <div className="mt-3">
                        <div className="d-flex align-items-center">
                            <button onClick={changeName} className="btn btn-primary mr-2"> Change name </button>
                            <b> {user.name} </b>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}
function mapStateToProps(state){
    return state = {
        user: state.userReducer
    }
}
function mapDispatchToProps(dispatch){
    return {
        changeName : (name) => {
            dispatch({type:"CHANGE_NAME",payload:name})
        }
    }
}

export default connect(mapStateToProps,mapDispatchToProps)(HomePage);